server:
  port: 8012

spring:
  application:
    name: service-verification-code

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1


